# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# set the operating systems to be tested
os:
   - linux
   - windows

# Set the python versions
python:
   - "2.7"
   - "3.5"
   - "3.6"

install:
   - pip install -r requirements.txt
   - pip install -r test-requirements.txt

script:
   - python setup.py develop
   - py.test
   

