# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python versions
python:
   - "2.7"
   - "3.5"
   - "3.6"
   - "3.7"

install:
   - pip install -r requirements.txt
   - pip install -r test-requirements.txt

script:
   - python setup.py develop
   - py.test
   

